### ISSUE TITLE
三角眼鏡の指摘事項

### ISSUE THREAD

**Issue by dwl398** [SeaeeesSan/SimpleFolderIcon#3]
各項目でissueにしたりしなかったりするといいかも

- [x] #4

![image](https://user-images.githubusercontent.com/47945028/132781975-ecafc689-183c-41c1-b457-bf23e6867375.png)

- [x] if () の後の改行のルールを統一する　基本的にコードが横長になると編集がしにくい（横にスクロールが必要になると見にくい）ので改行がおすすめ

![image](https://user-images.githubusercontent.com/47945028/132782172-096c78ba-bca1-41ff-ae8e-2a82f6acf224.png)

- こういう書き方とかだと横に伸びなくてコードレビューもしやすい

![image](https://user-images.githubusercontent.com/47945028/132782489-8d198b94-a2af-4d5f-9383-2d9fe722751b.png)

- [x] privateつけたり付けなかったりを統一する

![image](https://user-images.githubusercontent.com/47945028/132782716-dbfbba2a-5347-4d57-aad5-fa81cda1590d.png)

- [x] 機能追加とリファクタリングは同じコミットに含めない
    - リファクタリングしたい気持ちをグッと我慢してコミットを分ける　リファクタリングした部分だけStageしないでコミットとかでもOK

- [x] あとinitのコミットに成果物を含めるんじゃ無い！！！！！！！！！！！！！！！

**Comment by SeaeeesSan** [comment]
ありがとうございます！
